version: '3'

volumes:
  static:
  media:
  pg_data:

services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file:
      - .env
    volumes:
      - static:/app/collected_static 
      - media:/app/media
    depends_on:
      - db

  frontend:
    build: ./frontend/
    volumes:
      - static:/app/static
    env_file:
      - .env

  gateway:
    build: ./nginx/
    ports:
      - "9000:9000"
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend