version: '3'

volumes:
  static:
  media:
  pg_data:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: ${DOCKERHUB_USERNAME}/kittygram_backend
    env_file: .env
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - db
    restart: always

  frontend:
    image: ${DOCKERHUB_USERNAME}/kittygram_frontend
    volumes:
      - static:/app/static
    restart: always

  gateway:
    image: ${DOCKERHUB_USERNAME}/kittygram_gateway
    ports:
      - "9000:80"
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend
    restart: always