version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: lerasalamaha/kittygram_backend
    env_file: .env

    depends_on:
      - db
    volumes:
      - static:/app/static/
      - media:/app/media/


  frontend:
    image: lerasalamaha/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /app/static/
    volumes:
      - static:/app/static/

  gateway:
    image: lerasalamaha/kittygram_gateway
    depends_on:
      - backend
      - frontend
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/app/static/
      - media:/app/media/

