version: '3.8'

volumes:
  static:
  media:
  pg_data:

services:
  db:
    image: postgres:13
    container_name: db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-kittygram}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"  # Для внешнего подключения при необходимости

  backend:
    image: lerasalamaha/kittygram_backend
    container_name: backend
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-kittygram}
    volumes:
      - static:/app/collected_static
      - media:/app/media
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: kittygram_frontend
    container_name: frontend
    volumes:
      - static:/app/static
    env_file:
      - .env
    depends_on:
      - backend

  gateway:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: kittygram_gateway
    container_name: gateway
    ports:
      - "8080:80"  # Изменено с 9000 на стандартный HTTP порт
      - "8443:443" # Для HTTPS
    volumes:
      - static:/static
      - media:/media
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
      - frontend
    restart: always