name: Kittygram CI/CD

on:
  push:
    branches: [ main ]

env:
  DOCKERHUB_USERNAME: lerasalamaha  # Ваш логин Docker Hub

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: kittygram_user
          POSTGRES_PASSWORD: kittygram_password
          POSTGRES_DB: kittygram
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      
      - name: Run tests
        run: |
          cd backend
          python manage.py test

  build_and_push:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push backend
        run: |
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/kittygram_backend ./backend
          docker push ${{ env.DOCKERHUB_USERNAME }}/kittygram_backend
      
      - name: Build and push frontend
        run: |
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/kittygram_frontend ./frontend
          docker push ${{ env.DOCKERHUB_USERNAME }}/kittygram_frontend
      
      - name: Build and push gateway
        run: |
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/kittygram_gateway ./nginx
          docker push ${{ env.DOCKERHUB_USERNAME }}/kittygram_gateway

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/kittygram
            echo "POSTGRES_DB=kittygram" > .env
            echo "POSTGRES_USER=kittygram_user" >> .env
            echo "POSTGRES_PASSWORD=kittygram_password" >> .env
            echo "DB_NAME=kittygram" >> .env
            echo "DB_HOST=db" >> .env
            echo "DB_PORT=5432" >> .env
            echo "SECRET_KEY=11052004Lera" >> .env
            echo "DEBUG=False" >> .env
            echo "ALLOWED_HOSTS=*" >> .env
            docker compose down
            docker compose pull
            docker compose up -d
            docker compose exec backend python manage.py migrate
            docker compose exec backend python manage.py collectstatic --no-input